CREATE TABLE depoimentos (
  id INT AUTO_INCREMENT PRIMARY KEY,
  nome VARCHAR(100),
  email VARCHAR(100),
  curso VARCHAR(100),
  depoimento TEXT,
  data TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);